### ISSUE TITLE
snuba-subscription-consumer-* で発生しているエラーに対応する

### ISSUE THREAD

**Issue by shukawam** [cloudnativedaysjp/self-hosted-sentry#5]
```sh
Error: No such option: --delay-seconds
```

docker-compose.yml の以下部分を消したことによる影響を調べた上で消す or 代替オプションを探せば良さそう

```yaml
snuba-subscription-consumer-transactions:
    <<: *snuba_defaults
    command: subscriptions-scheduler-executor --dataset transactions --entity transactions --auto-offset-reset=latest --no-strict-offset-reset --consumer-group=snuba-transactions-subscriptions-consumers --followed-consumer-group=transactions_group --delay-seconds=60 --schedule-ttl=60 --stale-threshold-seconds=900
```
